### ISSUE TITLE
Scroll to top / Scroll to Index

### ISSUE THREAD

**Issue by Ivshti** [PeterStaev/NativeScript-Grid-View#10]
Usually, in android that would be:

```
gridView.android.setSelection(0)
```

(If I'm not mistaken)

But the implemented behaviour would be:
1. `.scrollTop()` function
2. Scroll to top when `items` is changed completely - new value altogether, rather than changed value (e.g. new observable array set) - this one is intuitive and sounds like a drop-in behaviour which makes sense; e.g., when you load more/change items, you keep the same array, but when you load different data, you change the array itself, and scrolling to top makes sense

Which one do you prefer?

**Comment by PeterStaev** [comment]
Hey @Ivshti , I feel like that instead of limiting this to scroll top only it will be better to have a `scrollToIndex()` function.

**Comment by Ivshti** [comment]
I agree 

The index should correspond to the element index?
