### ISSUE TITLE
Uncaught exception at first loading attempt

### ISSUE THREAD

**Issue by Ivshti** [PeterStaev/NativeScript-Grid-View#11]
This one is really weird.

The first loading attempt, I get this uncaught error;
```
JS: Error: Building UI from XML. @file:///app/./views/main/main.xml:59:13
JS:  ↳Building UI from XML. @file:///app/views/discover/discover.xml:55:9
JS:    ↳Module '/data/data/org.nativescript.stremio/files/app/tns_modules/nativescript-grid-view' not found for element 'nativescript-grid-view:GridView'.
JS:    ↳
JS:   Error calling module function 
JS: 
JS: TypeError: style.StylePropertyChangedHandler is not a function
JS: File: "/data/data/org.nativescript.stremio/files/app/tns_modules/nativescript-grid-view/grid-view.js, line: 222, column: 56
JS: 
JS: StackTrace: 
JS: 	Frame: function:'GridViewStyler.registerHandlers', file:'/data/data/org.nativescript.stremio/files/app/tns_modules/nativescript-grid-view/grid-view.js', line: 222, column: 57
JS: 	Frame: function:'', file:'/data/data/org.nativescript.stremio/files/app/tns_modules/nativescript-grid-view/grid-view.js', line: 230, column: 16
JS: 	Frame: function:'require', file:'', line: 1, column: 120
```

nativescript 1.5.1

The error was caught because the `.navigate` was unintentionally wrapped in try-catch.
The second time the `.navigate` to the page with the grid view was executed, it worked properly.

I have no idea how and why this may happen..

**Comment by Ivshti** [comment]
Some investigation:

Seems to be related to this:
https://github.com/bradmartin/nativescript-floatingactionbutton/pull/10

(sidenote: unfortunately, we cannot use latest nativescript because of a bug since 1.6 in overlaying video with other elements)

Why it works the second time: because it continues execution without registerHandlers

**Comment by PeterStaev** [comment]
The plugin supports {N} 1.6+. If you need to use it with an old version, you should use one of the previous releases, and apply any patches for breaking issues (like the `rowHeight`).
