### ISSUE TITLE
UIColor.clearColor is not a function

### ISSUE THREAD

**Issue by jalal** [PeterStaev/NativeScript-Grid-View#13]
When building, the message shows that clearColor is not a function:

`UIColor.clearColor is not a function. (In 'UIColor.clearColor()', 'UIColor.clearColor' is an instance of UIColor)`

Modifying nativescript-grid-view/grid-view-ios.js:116 solves the problem.

**Comment by PeterStaev** [comment]
Hey @jalal , this is because the plugin is not updated yet to latest {N} and so it does not work with XCode8+ and iOS10 SDK

**Comment by jalal** [comment]
Apart from that little thing, it does appear to work, at least, in my project.

**Comment by raditha** [comment]
Did you commented that line altogether in "grid-view-ios.js"? what was your modification @jalal ?

**Comment by jalal** [comment]
@raditha no, I changed the code. Made it an attribute, not a function...

**Comment by raditha** [comment]
@jalal  Thank you

**Comment by tpgalan** [comment]
Just for confirmation:

The change I made (and now works) is changing:

`this._ios.backgroundColor = UIColor.clearColor();`

to

`this._ios.backgroundColor = UIColor.clearColor;`

Is that right?

Thanks,

**Comment by raditha** [comment]
@tpgalan that is correct.Did the same modification and it works
