### ISSUE TITLE
itemTap function not working

### ISSUE THREAD

**Issue by raditha** [PeterStaev/NativeScript-Grid-View#14]
The function for itemTap dosent trigger when tested with the ios emulator.

**Comment by PeterStaev** [comment]
Hey @raditha , I just tested on the iOS simulator and the event is firing correctly. So seems something specific to your setup. Please provide more details if you are still experiencing the issue.

**Comment by PeterStaev** [comment]
No response from user, closing this one for now. In case you still have problems, please reopen and provide more details.

**Comment by KingAndroid** [comment]
Hello @PeterStaev 
How are you?
I have also met this issue.
Could you please have a look this video capture?

https://www.dropbox.com/s/4zlhz6xua1eerhw/gridview%20issue.mp4?dl=0
