### ISSUE TITLE
Example plugin not working

### ISSUE THREAD

**Issue by tpgalan** [PeterStaev/NativeScript-Grid-View#15]
Hi,

Maybe I'm doing something wrong, but the issue here is that I cannot use it. 
When I first copy the XML example and the I translate the TS to JS it shows:

> Successfully synced application org.nativescript.MyApp on device 70AE4041-7BB2-43C9-9A99-FB822DAA1762.
> objc[14385]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x126545998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x126367880). One of the two will be used. Which one is undefined.
> 1   0x10e910a6b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
> 2   0x10f09090e ffi_closure_unix64_inner
> 3   0x10f0912c2 ffi_closure_unix64
> 4   0x10fe18e70 -[UIViewController view]
> 5   0x10fce24b5 -[UIWindow addRootViewControllerViewIfPossible]
> 6   0x10fce2c06 -[UIWindow _setHidden:forced:]
> 7   0x10fcf6519 -[UIWindow makeKeyAndVisible]
> 8   0x10f09111d ffi_call_unix64
> 9   0x12b0525d0
> file:///app/tns_modules/ui/builder/builder.js:167:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:3:5
> 	 > Module '[....]MyApp.app/app/tns_modules/nativescript-grid-view' not found for element 'nativescript-grid-view:GridView'.
> 	   > UIColor.clearColor is not a function. (In 'UIColor.clearColor()', 'UIColor.clearColor' is an instance of UIColor)
> Dec 28 01:41:53 _____ com.apple.CoreSimulator.SimDevice.70AE4041-7BB2-43C9-9A99-FB822DAA1762.launchd_sim[5452] (UIKitApplication:org.nativescript.MyApp[0xeb5a][14385]): Service exited due to Segmentation fault: 11

I saw similar messages but not the same in the issue list, so I'm posting this as a new one.

The translated code I use for using JS is:

```
var observable = require("data/observable");
var observableArray = require("data/observable-array");
var pages = require("ui/page");
var gridView = require("nativescript-grid-view");
 
var viewModel = new observable.Observable;
 
exports.pageLoaded = function(args) 
{
    var page = args.object;
    var items = new observableArray.ObservableArray();
 
    for (var loop = 0; loop < 200; loop++)
    {
        items.push({ value: "test " + loop.toString() });
    }
    viewModel = new observable.Observable();
    viewModel.set("items", items);
 
    page.bindingContext = viewModel;
}
 
exports.gridViewItemTap = function (args)
{
    console.log("tap index " + args.index.toString());
}
 
exports.gridViewItemLoading = function (args)
{
    console.log("item loading " + args.index.toString())
}
 
exports.gridViewLoadMoreItems = function (args)
{
    console.log("load more items");
}

```

After that I run using a `tns run ios` and the previous message appears. I'm doing something wrong?

Thanks in advance

**Comment by PeterStaev** [comment]
Hey @tpgalan , this is the same problem as the one mentioned in #13. You can see a fix mentioned there.
