### ISSUE TITLE
Typescript/Angular example

### ISSUE THREAD

**Issue by shanika** [PeterStaev/NativeScript-Grid-View#17]
Hi, Could you please add a Typescript/Angular example as well. Thanks.

**Comment by PeterStaev** [comment]
Hey @shanika , there is no example, because the plugin does no support Angular yet. You can follow the discussion in #12

**Comment by deepak4u2006** [comment]
Hey @shanika , @PeterStaev 
`<ScrollView class="plansScroll" #plansScroll orientation="vertical" horizontalAlignment="left" width="100%">
    <WrapLayout orientation="horizontal" [id]="myIndex" (tap)="onPlanSectionTap($event)" class="plansScrollGrid m-5" #plansScrollGrid>
        <StackLayout *ngFor='let item of arrayMerchants; let myIndex = index' width="33.3%">
            <Image class="m-t-30 m-b-15" src="res://icon" width="80" height="80"></Image>
            <Label class="plansScrollGrid_Type m-5" minwidth="50" [text]='item.title' [color]='item.titleColor' horizontalAlignment="center" verticalAlignment="center" #plansScrollGridType textTransform="capitalize"></Label>
        </StackLayout>
    </WrapLayout>
</ScrollView>`
