### ISSUE TITLE
unable to achieve grid view in android

### ISSUE THREAD

**Issue by lsowmya** [PeterStaev/NativeScript-Grid-View#18]
XML:
<StackLayout
        xmlns="http://www.nativescript.org/tns.xsd"
        xmlns:gv="nativescript-grid-view"
        xmlns:Card="nativescript-cardview">

    <GridLayout row="1">
        <gv:GridView id="_listViewKPICards" items="{{ _kpiCards }}" colWidth="{{screenWidthsCol}}" backgroundColor="#f6f6f6" rowHeight="80">
            <gv:GridView.itemTemplate>

                <StackLayout>
                    <Card:CardView class="cardStyle" tap="navigateOnCardClick" margin="5" elevation="20">
                        <GridLayout rows="*, *" columns="*" horizontalAlignment="stretch">
                            <label fontSize="11" margin="5 5 0 5" id="key" text="{{ key }}" textWrap="true" className="alright" row="1" col="0" color="black"/>
                            <label fontSize="18" margin="0 5 5 5" text="{{ vPercent }}" textWrap="true" className="alright" row="0" col="0" color="#049FD9"/>
                        </GridLayout> 
                    </Card:CardView>
                 </StackLayout>

            </gv:GridView.itemTemplate>
        </gv:GridView>
    </GridLayout>

</StackLayout>
Package.json:
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.cisco.mbr",
    "tns-ios": {
      "version": "3.0.1"
    },
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/platform-browser": "^4.1.1",
    "@angular/router": "^4.1.1",
    "base-64": "^0.1.0",
    "nativescript-angular": "^3.0.0",
    "nativescript-cardview": "^2.0.1",
    "nativescript-collapsing-header": "2.0.0",
    "nativescript-exit": "^1.0.0",
    "nativescript-fingerprint-auth": "4.0.0",
    "nativescript-floatingactionbutton": "3.0.0",
    "nativescript-grid-view": "3.0.0",
    "nativescript-intl": "3.0.0",
    "nativescript-loading-indicator": "2.3.2",
    "nativescript-master-technology": "^1.1.0",
    "nativescript-oauth": "file:../nativescript-oauth",
    "nativescript-statusbar": "1.0.0",
    "nativescript-telerik-ui": "2.0.1",
    "rxjs": "^5.4.0",
    "tns-core-modules": "^3.0.0",
    "tslint": "^5.4.3",
    "utf8": "^2.1.2",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "babel-traverse": "^6.22.1",
    "babel-types": "^6.22.0",
    "babylon": "^6.15.0",
    "filewalker": "^0.1.3",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.4.4",
    "tns-platform-declarations": "^3.0.0",
    "tslint": "^5.4.3",
    "typescript": "^2.3.4"
  }
}

From the above code am trying to achieve Grid view pattern with native script card view. Above piece of code works perfectly fine in iOS but  breaks in android.
Any suggestions to solve my problem.

**Comment by PeterStaev** [comment]
Hey @lsowmya , from the package it seems you are using angular, but the example seems like a plain NS. Keep in mind that Angular is not supported bu this plugin yet. 

If you are using plain NS, you can try to set change the `StackLayout` with a `GridLayout` and also try to set the `verticalAlignment="stretch"` of the `CardView` and wrapping layout. 
Another idea is to try and remove the wrapping layout and in the template to have directly the `CardView`

**Comment by lsowmya** [comment]
None of the above options are working for me. With gridview its not throwing any errors but the page is blank.
If i replace gridview with listview its works fine..
did i miss something that breaking. [Issue exists only in android, iOS works perfectly fine.]
XML:
<StackLayout xmlns="http://www.nativescript.org/tns.xsd" xmlns:Card="nativescript-cardview" xmlns:gv="nativescript-grid-view" id="_kpiCharts">
      <gv:GridView id="_listViewKPICards" items="{{ items }}" colWidth="{{ screenWidthsCol }}" backgroundColor="#f6f6f6" rowHeight="80">
         <gv:GridView.itemTemplate>
            <Card:CardView class="cardStyle" verticalAlignment="stretch" tap="navigateOnCardClick" margin="5" elevation="20">
               <label fontSize="11" text="{{ value }}" textWrap="true" color="black" />
            </Card:CardView>
         </gv:GridView.itemTemplate>
      </gv:GridView>
</StackLayout>

**Comment by PeterStaev** [comment]
@lsowmya , try replacing `CardView` with a simple view like `GridLayout`. It could be some measurement problem of the `CardView` plugin on android.

**Comment by lsowmya** [comment]
I tried all possible ways. just gave label within grid-view wrapped with grid layout without any cardview plugin. still its not working.

**Comment by PeterStaev** [comment]
@lsowmya , there is something wrong with your styles/setup. I suggest you start off with the demo project in this repo and then add your changes to it in order to see which one is breaking it.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please reopen and provide more details.
