### ISSUE TITLE
Passing variables to gridview xml

### ISSUE THREAD

**Issue by fonshua** [PeterStaev/NativeScript-Grid-View#3]
How do I set the column width and row height of the gridview dynamically? I try to pass variable to the xml but it doesn't seem to work:

```
    <GridLayout>
        <gv:GridView items="{{ items }}"  verticalSpacing="12" horizontalSpacing="0" colWidth="{{ column_width }}" rowHeight="{{ row_height }}" itemTap="gridViewItemTap" itemLoading="gridViewItemLoading" loadMoreItems="gridViewLoadMoreItems" class="gridview" >
```

**Comment by PeterStaev** [comment]
What you did, is the correct way to make columns/rows dynamically. But note that for Android there was a problem that the binding was not applied (#1). Make sure you are using the latest version of the plugin.

**Comment by fonshua** [comment]
Sorry for confusing you, not sure if the problem is still related to the plugin or NativeScripts core modules, if I pass the variable to GridLayout itself, I will get the error message "Cannot parse item spec from string: {{ row_height }}
```
      <GridLayout class="grid" columns="148" rows="{{ row_height }},45,45">
        <Image class="image" col="0" row="0" src="{{ image }}" />
        <Label class="name" col="0" row="1" text="{{ name }}" />
        <Label class="id" col="0" row="2" text="{{ id }}" />
      </GridLayout>
```

I check that error seems to be from https://github.com/NativeScript/NativeScript/blob/master/ui/layouts/grid-layout/grid-layout-common.ts#L322

Did I miss anything?

**Comment by PeterStaev** [comment]
Aha, yes, you are mistaken my GridView widget with the {N}'s GridLayout one :) 

Currently i don't think it is possible to make dynamic columns/rows in the GridLayout widget. So you might post a suggestion to the NativeScript repository.
