### ISSUE TITLE
How to display the entire array data in a row in demo-ng?

### ISSUE THREAD

**Issue by LHLK** [PeterStaev/NativeScript-Grid-View#33]
I just download the plugin and I'm wondering if it's possible to display the entire data, for e.g. from your demo-ng items array: { id: 1, name: "Ter Stegen", role: "Goalkeeper" } in the same row.  Currently, only the name property was shown. In other words, could the html/android display in the following way:
[Capable to scroll both vertically and horizontally ]
Row 0:  id = 1 (css border), name = Ter Stegen (css border), role = Goalkeeper (css border), etc...
Row 1:  id=2 (css border), name=Piqué (css border), role=Defender (css border), etc (scroll horizontally)
. 
Row x: ( scroll up vertically)

Thanks. 
LH

**Comment by PeterStaev** [comment]
Hey @LHLK , if you want to display single item per row, why dont you use the built-int `ListView` plugin in nativescript? I haven't tried it but I guess you can simulate ListView by specifying `colWidth="100%"`

**Comment by LHLK** [comment]
Thank you Sir for your advice and your plugin is indeed very good.
