### ISSUE TITLE
How to hide scroll bar 

### ISSUE THREAD

**Issue by LSmint** [PeterStaev/NativeScript-Grid-View#36]
I want to hide the vertical scrollbar view in the gridview, anyone can provide some advice ?

**Comment by PeterStaev** [comment]
Hey @LSmint , from what not sure what platform is this, but from what I see on android this is not possible: https://stackoverflow.com/a/27298868/5272836. 

For iOS you should be able to do it via:
```ts
const gv = page.getViewById<GridView>("gv");
gv.ios.setShowsHorizontalScrollIndicator(false);
gv.ios.setShowsVerticalScrollIndicator(false);
```

**Comment by LSmint** [comment]
Thanks @PeterStaev your answer, it's works! I yet to try Android but may try for following this. 
android.setVerticalScrollBarEnabled(false);
android.setHorizontalScrollBarEnabled(false);
android.requestDisallowInterceptTouchEvent(true);

**Comment by PeterStaev** [comment]
No further response so closing this one for now.
