### ISSUE TITLE
nested vertical GridView inside horizontal GridView cause ios position problems

### ISSUE THREAD

**Issue by racknoris** [PeterStaev/NativeScript-Grid-View#45]
I have 5 cells in a horizontal `GridView`, each contains a vertical `GridView` with 25 cells, tested only in iOS

In order to see the problem, i do the following:
1. When the application loads, we see the 1st page- scroll it up a bit.
2. Scroll horizontally to page 4, see that the `y` offset is the same as page 1, even though we didn't change it.
3. Scroll horizontally back to page 2, and scroll up a bit
4. Scroll horizontally to page 5, and see that it has the same `y` offset as page 2

video of the issue:
https://drive.google.com/open?id=18qvAZWbjZk4qOPK-7aMikfVdrcLgaq1j

Is there a workaround I can use?

In order to create the sample I used the code in your [demo-ng/app/item](https://github.com/PeterStaev/NativeScript-Grid-View/tree/master/demo-ng/app/item) folder and changed 2 files:

1. `items.component.html`:

```
<GridLayout rows="*" columns="*">

    <GridView [items]="outerItems" colWidth="100%" rowHeight="100%" orientation="horizontal">
        <ng-template let-outerItem="item" let-i="index">
            <GridLayout rows="*" columns="*">
    
                <Label [text]="'Page ' + (i + 1)" color="#f0f" width="100" verticalAlignment="top"></Label>

                <GridView row="0" [items]="outerItem" colWidth="100%" rowHeight="200" orientation="vertical">
                    <ng-template let-item="item">            
                        <StackLayout [nsRouterLink]="['/item', item.id]" borderColor="blue" borderWidth="2" borderRadius="5" verticalAlignment="stretch" class="list-group-item" [class.odd]="odd">
                            <Label verticalAlignment="center" [text]="item.name" class="list-group-item-text" textWrap="true"></Label>
                        </StackLayout>
                    </ng-template>
                </GridView>

            </GridLayout>
        </ng-template>
    </GridView>

</GridLayout>
```

2. `items.component.ts`:

```
import { Component, OnInit } from "@angular/core";

import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    items: Item[];
    outerItems: any = [];

    // This pattern makes use of Angular’s dependency injection implementation to inject an instance of the ItemService service into this class.
    // Angular knows about this service because it is included in your app’s main NgModule, defined in app.module.ts.
    constructor(private itemService: ItemService) { }

    ngOnInit(): void {
        this.items = this.itemService.getItems();

        for (let i = 0; i < 5; i++) {
            this.outerItems.push(this.items);
        }
    }

    public templateSelector(item: Item) {
        return item.role;
    }
}
```

**Comment by racknoris** [comment]
@PeterStaev Is this in the scope of the project?
Is there a workaround you can think of?

**Comment by PeterStaev** [comment]
@racknoris , this problem happens because the GridView re-uses views so that it does not take much memory on large projects. So you need to take care and reset your view. For example I think it would be possible to use the `itemLoading` event and then call the `scrollToIndex()`

**Comment by racknoris** [comment]
I see, thank you
