### ISSUE TITLE
GridView exception on iOS with runtime 5 - did not call setMeasuredDimension()

### ISSUE THREAD

**Issue by iianev** [PeterStaev/NativeScript-Grid-View#47]
Application closed with the exception below.

To reproduce - upgrade TNS to latest version - this install new runtime and TnsNativeModules.

After the upgrade the angular demo no longer works on iOS - seems to work ok on Android.

Exception StackTrace
-----------
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:3726:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x106d022c1 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x106d32cf0 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x1076de486 ffi_closure_unix64_inner
4   0x1076dee6a ffi_closure_unix64
5   0x10acf3198 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:]
6   0x10acf884f -[UICollectionView _updateVisibleCellsNow:]
7   0x10acfe076 -[UICollectionView layoutSubviews]
8   0x10b98b795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
9   0x10cf13b19 -[CALayer layoutSublayers]
10  0x10cf189d3 CA::Layer::layout_if_needed(CA::Transaction*)
11  0x10ce917ca CA::Context::commit_transaction(CA::Transaction*)
12  0x10cec897e CA::Transaction::commit()
13  0x10b4bc2d0 __34-[UIApplication _firstCommitBlock]_block_invoke_2
14  0x109f5f62c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
15  0x109f5ede0 __CFRunLoopDoBlocks
16  0x109f59654 __CFRunLoopRun
17  0x109f58e11 CFRunLoopRunSpecific
18  0x1111821dd GSEventRunModal
19  0x10b4a181d UIApplicationMain
20  0x1076decad ffi_call_unix64
21  0x131f5d640
**JavaScript stack trace:**
1   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124
2   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
3   @file:///app/tns_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:51:68
4   eachLayoutChild@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:143:21
5   onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:49:29
6   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:55:27
7   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
8   _layoutCell@file:///app/tns_modules/nativescript-grid-view/grid-view.js:209:37
9   _prepareCell@file:///app/tns_modules/nativescript-grid-view/grid-view.js:199:29
10  collectionViewCellForItemAtIndexPath@file:///app/tns_modules/nativescript-grid-view/grid-view.js:273:27
11  UIApplicationMain@[native code]
12  start@file:///app/tns_modules/tns-core-modules/application/<…>
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(54)
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   start@file:///app/tns_modules/tns-core-modules/application/application.js:273:26
2   run@file:///app/tns_modules/tns-core-modules/application/application.js:301:10
3   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:158:26
4   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:92:38
5   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:81:26
6   anonymous@file:///app/main.js:13:57
7   evaluate@[native code]
8   moduleEvaluation@:1:11
9   promiseReactionJob@:1:11
)
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(54)
at
1   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124
2   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
3   @file:///app/tns_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:51:68
4   eachLayoutChild@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:143:21
5   onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:49:29
6   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:55:27
7   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
8   _layoutCell@file:///app/tns_modules/nativescript-grid-view/grid-view.js:209:37
9   _prepareCell@file:///app/tns_modules/nativescript-grid-view/grid-view.js:199:29
10  collectionVie<…>

**Comment by throwingdarts** [comment]
@PeterStaev is there a fix for this in the near future by chance or do we need to degrade our runtime for now? Thanks.

**Comment by PeterStaev** [comment]
@throwingdarts , it is on my todo list, but cant give you an ETA.
