### ISSUE TITLE
PullToRefresh?

### ISSUE THREAD

**Issue by razorsyntax** [PeterStaev/NativeScript-Grid-View#49]
Is it possible to create a Pull to Refresh with this plugin

I've experimented with the PullToRefresh plugin to implement this to no avail.  See my example, not working code below.

```
<PullToRefresh (refresh)="pullToRefresh($event)">
    <ListView class="list-group">
        <GridLayout>
            <GridView [items]="someItems" (itemTap)="loadThisPage($event)">
                <ng-template let-some="item">
                    <StackLayout minHeight="100">
                        <Label [text]="some"></Label>
                    </StackLayout>
                </ng-template>
            </GridView>
        </GridLayout>
    </ListView>
</PullToRefresh>
```

Any ideas?

**Comment by razorsyntax** [comment]
Update: Sadly, I ended up uninstalling GridView and implemented a custom version.  I'll definitely check back to see if this is something that's possible with GridView in the future.

**Comment by PeterStaev** [comment]
Hey @razorsyntax , using Pull To Refresh is possible with the plugin but you are doing it wrong. You wrapped your listview with the PullToRefresh and not the GridView.

**Comment by razorsyntax** [comment]
Oh sweet!  But how does the order go?

--<Gridview>
------<PullToRefresh>
----------<other-stuff></other-stuff>
------</PullToRefresh>
--</Gridview>

Your reply wasn't too clear.

**Comment by PeterStaev** [comment]
@razorsyntax ,you need to **wrap** the GridView just like you do with the ListView. 
```
<PullToRefresh>
    <Gridview>
        <other-stuff></other-stuff>
    </Gridview>
</PullToRefresh>
```
