### ISSUE TITLE
blank screen in android

### ISSUE THREAD

**Issue by racknoris** [PeterStaev/NativeScript-Grid-View#51]
I get a blank screen in Android when trying to use GridView element in an empty project. However, when using `npm run demo-ng-android`, the demo runs perfectly. Also, in iOS it works great in an empty project

Steps to reproduce: 
1. `tns create emptyProject --ng`
2. copy the `item` folder from the demo to the new project
3. place the code in the modules folder, so the new element could be used
4. `tns run android`
5. the gridview does not show anything

Could it be something with my settings? I was trying to use tns 5.0.0/5.1.0/4.0.0, none worked

**Comment by racknoris** [comment]
Decided to start from the basis: I use `tns-template-hello-world-ng` as the starter template, and it appears that the default is currently version 5.3.1. What I did is going back to version 5.0.0, and it works.
Will now try to see where exactly it breaks and update here

note for future readers: in order to get the 5.0.0 version of the template-
`tns create ngSample --template tns-template-hello-world-ng@5.0.0`

**Comment by racknoris** [comment]
I found that the problem was `nativescript-angular` above version 7.1.2 - the plugin didn't work on Android for versions 7.2.1/7.2.0

Updated package.json that works:
```
{
  "nativescript": {
    "id": "org.nativescript.gridViewAndroid",
    "tns-android": {
      "version": "5.2.1"
    },
    "tns-ios": {
      "version": "5.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "nativescript-angular": "~7.1.2", // << replaced
    "nativescript-grid-view": "^5.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~5.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.2.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "~7.2.0",
    "nativescript-dev-typescript": "~0.8.0",
    "nativescript-dev-webpack": "~0.20.0"
  },
  "gitHead": "f548ec926e75201ab1b7c4a3a7ceefe7a4db15af",
  "readme": "NativeScript Application"
}
```

@PeterStaev Should I open a new issue for this? Is it still a support issue or a bug?

**Comment by PeterStaev** [comment]
@racknoris , thanks for the details. I was able to simulate the problem on my end when upgrading the angular deps. I will see what can be done. For the time-being you should downgrade NG deps if this is urgent for your project.

**Comment by racknoris** [comment]
@PeterStaev no problem
From NativeScript perspective, would it be ok if I just downgrade the `nativescript-angular` and keep the others in version 7.2.0? I mean, could it cause problems?

**Comment by PeterStaev** [comment]
@racknoris , afaik the "supported" wait is to have `nativescript-angular` and `@angular/*` deps on the same minor version. But you could try.

**Comment by racknoris** [comment]
@racknoris I see
Ok, thank you

**Comment by PeterStaev** [comment]
@racknoris , the new version (5.1) on npm should resolve this problem.

**Comment by racknoris** [comment]
Ok
thank you
