### ISSUE TITLE
Observable Array not refreshing in the UI

### ISSUE THREAD

**Issue by Izrab** [PeterStaev/NativeScript-Grid-View#52]
My app is a NativeScript Core JS/XML project, written in Vanilla JavaScript and it is ran on Android 5.0

I have an Observable Array as GridView items, if user tab on a GridView item, a modal page is displayed to change the value of the item, when user changes the value and tabs "Done" button, the value is returned as result from the modal page, then the result is set to the Observable Array position in place of the old value, like this:
groceryList.setItem(indexarr, result);

indexarr is index number, and result is the returned value from the modal page.

With console.log, I assured that the Observable Array value is updated and has no problem, but it is not updated or refreshed on the GridView UI, 
I used the following code to try to reinforce update (it worked for me for ListView), but not worked for GridView:
page.bindingContext = viewModel;

Here are some main pieces of code, because of copyright concerns, I prefer not to release all code.
[analysis-page.txt](https://github.com/PeterStaev/NativeScript-Grid-View/files/3055903/analysis-page.txt)

**Comment by PeterStaev** [comment]
Hey @Izrab , I cannot simulate this behaviour. I edited the demo app in this repo and changed the item tap handler to the following:
```ts

export function gridViewItemTap(args: GridItemEventData) {
    console.log("tap index " + args.index.toString());
    const items: ObservableArray<{ value: string }> = viewModel.get("items");
    items.setItem(args.index, { value: "NEW VALUE" });
    console.log(items.getItem(args.index));
}
```
When I tap on any item its text is correctly updated.

**Comment by Izrab** [comment]
I can't use this code and I don't fully understand it, because my app is Vanilla JavaScript, not TypeScript.
Can you rewrite the code in Vanilla JavaScript?

**Comment by PeterStaev** [comment]
@Izrab , I would strongly suggest you migrate your project to TypeScript, and the JS code is not much different than the above:
```js
exports.gridViewItemTap = function (args) {
    console.log("tap index " + args.index.toString());
    var items = viewModel.get("items");
    items.setItem(args.index, { value: "NEW VALUE" });
    console.log(items.getItem(args.index));
}
```

**Comment by Izrab** [comment]
Alhamdulilah, it updates and refreshes now, issue solved.
Thanks a lot.
