### ISSUE TITLE
Error after install plugin

### ISSUE THREAD

**Issue by PabloPG** [PeterStaev/NativeScript-Grid-View#53]
Hello, after installation of the plugin i got this error:

` What went wrong:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
> Could not determine artifacts for com.android.support:recyclerview-v7:28.0.0
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/support/recyclerview-v7/28.0.0/recyclerview-v7-28.0.0.aar'.
      > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/support/recyclerview-v7/28.0.0/recyclerview-v7-28.0.0.aar'.
         > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If i remove plugin this error not occur

> TNS Version 5.2.3

**Comment by PeterStaev** [comment]
@PabloPG , seems you have some problems downloading/connecting to the google Maven repositories. Please try again or on another machine.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
