### ISSUE TITLE
Nativescript 5.4.0-androidx

### ISSUE THREAD

**Issue by DevDomRaven** [PeterStaev/NativeScript-Grid-View#56]
Trying to run or build a nativescript project that uses grid-view and i get "TypeError: Cannot read property "widget' of undefined"

app/tns_modules/nativescript-grid-view/grid-view.js, line: 364, column: 25

Worked fine is earlier versions of Nativescript.

**Comment by throwingdarts** [comment]
You might try clearing your cache and re uild.

**Comment by PeterStaev** [comment]
Hey @DevDomRaven , NS 5.4 does not have support for androidx (this will come with NS 6.0 later in the summer). If you are getting any errors related to androidx you should read http://fluentreports.com/blog/?p=942 and adjust your project accordingly.

**Comment by DevDomRaven** [comment]
That worked Peter, thanks.
