### ISSUE TITLE
Nativescript 6 support

### ISSUE THREAD

**Issue by mobilemindtec** [PeterStaev/NativeScript-Grid-View#65]
Change `include.gradle`

```
dependencies {
    def supportVer = project.hasProperty("supportVersion") ? supportVersion : "1.2.0-alpha01";
    compile "androidx.recyclerview:recyclerview:$supportVer"
}
```

Change `grid-view.android.js`

`android.support.v7.widget` to `androidx.recyclerview.widget`

**Comment by PeterStaev** [comment]
@mobilemindtec , instead of posting this as an issue, please submit a PR that fixes related code. I will be more than happy to merge it and push a new version on NPM 👍

**Comment by mobilemindtec** [comment]
Ok, is done.
