### ISSUE TITLE
Scroll Horizontally

### ISSUE THREAD

**Issue by girishgkg** [PeterStaev/NativeScript-Grid-View#7]
Is it possible to change the scroll direction to Horizontal ? Thanks

**Comment by PeterStaev** [comment]
Hey @girishgkg , sadly currently this is not supported by the plugin.

**Comment by Ivshti** [comment]
+1 
I guess this would not be possible with GridView on android? Perhaps RecyclerView? @PeterStaev

**Comment by PeterStaev** [comment]
@Ivshti , yes for android `GridView` cannot be horizontally scrolled so the android part will have to be rewritten using `RecyclerView`. 

The funny part is that when I initially started this plugin I had planned to use `RecyclerView`but back then there was no support to add custom dependencies in {N} plugins that the `RecyclerView` support lib was not included by default...

**Comment by PeterStaev** [comment]
Thanks to @m-abs this is now available in version 3.2!
