### ISSUE TITLE
Typescript cannot reference 'UICollectionView' and 'android'

### ISSUE THREAD

**Issue by jalal** [PeterStaev/NativeScript-Grid-View#8]
When building using Typescript, the following (non fatal) errors appear in the console:

`error TS2304: Cannot find name 'UICollectionView'.`
`error TS2503: Cannot find namespace 'android'.`

This can be fixed by changing lines 43,44 in 'grid-view.d.ts' from 

`
ios: UICollectionView;   
android: android.widget.GridView;
`

to

` 
ios: any; /* UICollectionView; */    
android: any; /* android.widget.GridView; */
`

**Comment by PeterStaev** [comment]
Hey @jalal , I know of this but I like to keep my TS as strongly typed as possible. This will be resolved once {N} team releases the android/ios `d.ts` files to `tsd` / `npm`. So for the time being I will not change the definitions. If you want the error to go away simply download the android and ios definitions from the {N} repository and include them in your project:
https://github.com/NativeScript/NativeScript/blob/master/ios.d.ts
https://github.com/NativeScript/NativeScript/blob/master/android17.d.ts
