### ISSUE TITLE
Issue when changing rowHeight - recycling old rows

### ISSUE THREAD

**Issue by Ivshti** [PeterStaev/NativeScript-Grid-View#9]
Hello - great plugin!

In case of initializing it once with a specific rowHeight, and then changing that rowHeight, some rows (seemingly random) remain with the old rowHeight

E.g.:
<img width="1293" alt="before" src="https://cloud.githubusercontent.com/assets/1247629/14710621/cf4c230c-07de-11e6-81f7-dd61fefb7fc9.png">
<img width="1293" alt="after - case1" src="https://cloud.githubusercontent.com/assets/1247629/14710623/cf73e3a6-07de-11e6-8b9c-cf72c5a1b0ea.png">
<img width="1293" alt="after - case2" src="https://cloud.githubusercontent.com/assets/1247629/14710622/cf730206-07de-11e6-89e7-00e9538062ce.png">

Is there any way to manually trigger a re-set when loading a new rowHeight?

**Comment by PeterStaev** [comment]
Hey @Ivshti , this is now resolved in the 1.3.3 version published to NPM. Thanks for reporting this!

**Comment by Ivshti** [comment]
@PeterStaev impressive response, thanks!

I'm a bit worried that it won't solve the issue though, as I tried the same thing, minus the .width setting. I also tried re-setting width/height on all the _realizedItems upon refresh.

I'll try ASAP and report the result

**Comment by Ivshti** [comment]
Indeed works fantastically!
